# Generated by Django 4.0.5 on 2022-07-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='image',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='price',
        ),
    ]
