# Generated by Django 4.0.5 on 2022-07-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_sneakers_type_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='male',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(verbose_name=(('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'))),
        ),
    ]
