# Generated by Django 4.0.5 on 2022-07-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_name_brand_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_date'], 'verbose_name': 'Coment', 'verbose_name_plural': 'Coments'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sneakers', 'verbose_name_plural': 'Sneakers'},
        ),
        migrations.AlterModelOptions(
            name='sneakerstype',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
    ]
