# Generated by Django 4.0.5 on 2022-07-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
