# Generated by Django 4.0.5 on 2022-07-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_brand_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sneakers_type',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
