# Generated by Django 4.0.5 on 2022-07-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_like_image_favorites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SneakersType',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Сategories'},
        ),
    ]
