# Generated by Django 4.0.5 on 2022-07-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_sneakerstype_category_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
